image: "rust:latest"

test:cargo:
  script:
  - rustup default 1.55.0
  - rustup show
  - rustc --version && cargo --version
  - rustup component add rust-src
  - cargo test --all
  - cargo bench --all